BigInteger support
qdrant/openapi-typescript-fetch pull request #7
Opened 2023-12-10 20:54 UTC by kartik-gupta-ij

#6
Fixed using [json-bigint](https://www.npmjs.com/package/json-bigint)

2023-12-11 19:35 UTC, generall commented on package.json
> +  },
why this is changed?

2023-12-11 19:36 UTC, generall commented
shouldn't this be also changed https://github.com/qdrant/openapi-typescript-fetch/blob/f33b84870048e75efe68e1ebaf6876bf87548ab1/src/fetcher.ts#L97C2-L97C79 ?

2023-12-11 19:37 UTC, kartik-gupta-ij commented on package.json
> +  },
Those package has vulnerabilities

2023-12-12 15:25 UTC, kartik-gupta-ij commented
> shouldn't this be also changed https://github.com/qdrant/openapi-typescript-fetch/blob/f33b84870048e75efe68e1ebaf6876bf87548ab1/src/fetcher.ts#L97C2-L97C79 ?

Fixed

2024-02-02 09:18 UTC, generall approved these changes

2024-02-04 15:40 UTC, Rendez commented on src/fetcher.ts
I think we should default to using BigInt, as [all modern browsers have now native support for it](https://caniuse.com/bigint). That way we tell the lib to internally avoid using `bignumber.js`:

`const JSONbigNative = JSONbig({ useNativeBigInt: true });`

2024-02-04 15:40 UTC, Rendez commented on package.json
> +  },
I would encourage you to explore more modern alternatives. This one was last published 4 years ago, and it seems to have quite a few [issues opened](https://github.com/sidorares/json-bigint/issues).

I found one that might be a better candidate: https://github.com/Ivan-Korolenko/json-with-bigint/blob/main/json-with-bigint.js (much, much smaller and simpler and perhaps even faster?) from this S.O. discussion: https://stackoverflow.com/a/69644630

2024-02-07 19:04 UTC, kartik-gupta-ij commented on package.json
> +  },
@Rendez, The vulnerabilities exist in `jest`, `msw`, `@typescript-eslint`, `jest-environment-jsdom`, and `@changesets/cli`, and they have not been resolved yet.

2024-02-08 13:45 UTC, Rendez commented on package.json
> +  },
It's not just the vulnerabilities, you're adding a massive outdated and unmaintained library, that is my concern.

2024-02-08 13:46 UTC, Rendez commented on package.json
> +  },
> @Rendez, The vulnerabilities exist in `jest`, `msw`, `@typescript-eslint`, `jest-environment-jsdom`, and `@changesets/cli`, and they have not been resolved yet.

Can't we update these libraries to latest? Do they still have these vulnerabilites after updating?

2024-02-08 13:52 UTC, Rendez requested changes

2024-02-08 13:52 UTC, Rendez commented on tsconfig.base.json
> +        "lib": ["dom", "dom.iterable", "es2019", "esnext"],
Please follow this convention: https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping

2024-02-08 13:52 UTC, Rendez commented on src/jsonParser.ts
> +export type Json =
Why did you add:
```json
{
 "dependencies": {
    "json-with-bigint": "^2.1.0"
  }
}
```

And then copied the [source](https://github.com/Ivan-Korolenko/json-with-bigint/blob/main/json-with-bigint.js) here?

2024-02-08 13:52 UTC, Rendez commented on test/fetch.test.ts
>    it(`POST /accepted`, async () => {
We should test the conversion and parsing of responses with big int.

2024-02-16 10:40 UTC, kartik-gupta-ij commented on package.json
> +  },
Yes, they do!

2024-02-16 11:29 UTC, Rendez commented on src/jsonParser.ts
> +export type Json =
I much rather have the dependency in case new versions with fixes happen, etc.

2024-02-19 09:06 UTC, Rendez approved these changes

2024-02-19 16:26 UTC, merged